name: Build Ashes of Dereliction

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  PROJECT_PATH: rpg_v1.8
  EXPORT_NAME: AshesOfDereliction
  EXPORT_PRESET: Windows Desktop

jobs:
  build:
    name: Build Windows
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Télécharger le dépôt
        uses: actions/checkout@v4

      - name: 🎮 Installer Godot 4.7.1
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.7.1"
          include-templates: true

      - name: ✅ Vérifier Godot
        run: godot --version

      - name: 📖 Lire la version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 📁 Créer le dossier Build
        run: mkdir -p Build

      - name: 🛠 Exporter le jeu
        working-directory: ./${{ env.PROJECT_PATH }}
        run: |
          godot --headless --path . --export-release "${{ env.EXPORT_PRESET }}" "../Build/${{ env.EXPORT_NAME }}.exe"

      - name: 📦 Créer le ZIP
        run: |
          cd Build
          zip -r "../${{ env.EXPORT_NAME }}-v${VERSION}.zip" .

      - name: 📤 Envoyer le ZIP en Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AshesOfDereliction-v${{ env.VERSION }}
          path: AshesOfDereliction-v${{ env.VERSION }}.zip